# OpenRouter + model routing
openrouter_base_url: "https://openrouter.ai/api/v1"   # OpenAI-compatible endpoint
model: "openai/gpt-5-mini"                  # any OpenRouter model id works
temperature: 0

# LangSmith tracing
langsmith_project: "dev-project"

# Demo thread id (preserves conversation history via checkpointer)
thread_id: "demo-thread-001"

# Paths
paths:
  system_prompt: "prompts/system.txt"
  dataset_path: "data/sample.jsonl"
